#!/usr/bin/env bash

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config layout bsp



yabai -m rule --add label="LICEcap" app="^licecap$" manage=off
